language: php

php:
    - 5.3
    - 5.4

services: mysql

before_script:
    - mysql -u root -p'' < Tests/Conf/Sql/Setup/DbTestSetup.sql
    - mysql -u root -p'' < Tests/Conf/Sql/Setup/InformationSchemaTestSetup.sql

script:
    - phpunit --coverage-text --configuration Tests/Conf/phpunit.xml

after_script:
    - php ./Tests/Conf/teardownDatabases.php
